Replaces cache sanitization steps. Tries fixing actions indentation.

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -90,66 +90,64 @@ jobs:
 
       runs-on: blacksmith-4vcpu-ubuntu-2404
       strategy:
-          fail-fast: false
-          matrix:
-              python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
-              toxenv: ['redis', 'rabbitmq', 'rabbitmq_redis']
+        fail-fast: false
+        matrix:
+          python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
+          toxenv: ['redis', 'rabbitmq', 'rabbitmq_redis']
 
       services:
-          redis:
-              image: redis
-              ports:
-                  - 6379:6379
-              env:
-                  REDIS_HOST: localhost
-                  REDIS_PORT: 6379
-          rabbitmq:
-              image: rabbitmq
-              ports:
-                  - 5672:5672
-              env:
-                  RABBITMQ_DEFAULT_USER: guest
-                  RABBITMQ_DEFAULT_PASS: guest
+        redis:
+          image: redis
+          ports:
+            - 6379:6379
+          env:
+            REDIS_HOST: localhost
+            REDIS_PORT: 6379
+        rabbitmq:
+          image: rabbitmq
+          ports:
+            - 5672:5672
+          env:
+            RABBITMQ_DEFAULT_USER: guest
+            RABBITMQ_DEFAULT_PASS: guest
 
       steps:
-          -   name: Install apt packages
-              run: |
-                  sudo apt-get update && sudo apt-get install -f libcurl4-openssl-dev libssl-dev libgnutls28-dev httping expect libmemcached-dev
+        - name: Install apt packages
+          run: |
+            sudo apt-get update && sudo apt-get install -f libcurl4-openssl-dev libssl-dev libgnutls28-dev httping expect libmemcached-dev
+        
+        - uses: actions/checkout@v4
+        - name: Set up Python ${{ matrix.python-version }}
+          uses: useblacksmith/setup-python@v6
+          with:
+            python-version: ${{ matrix.python-version }}
+            allow-prereleases: true
+            cache: 'pip'
+            cache-dependency-path: '**/setup.py'
 
-          -   uses: actions/checkout@v4
+        - name: Install tox
+          run: python -m pip install --upgrade pip 'tox' tox-gh-actions
 
-          -   name: Clean .pyc files
-              run: |
-                  find . -type f -name "*.pyc" -delete
-                  find . -type d -name "__pycache__" -exec rm -r {} +
+        - name: Clean pyc/__pycache__ and pytest cache
+          run: |
+            find . -type f -name "*.pyc" -delete
+            find . -type d -name "__pycache__" -exec rm -r {} +
+            python -m pip install pytest
+            pytest --cache-clear || true
 
-          -   name: Clear pytest cache
-              run: pytest --cache-clear || true
+        - name: Show test_quorum_queue_qos_cluster_simulation.py
+          run: |
+            echo ">>> test_quorum_queue_qos_cluster_simulation.py:"
+            cat t/integration/test_quorum_queue_qos_cluster_simulation.py || echo "File not found"
 
-          -   name: Print current test file
-              run: cat t/integration/test_quorum_queue_qos_cluster_simulation.py || echo "Test file not found"
-
-          -   name: Set up Python ${{ matrix.python-version }}
-              uses: useblacksmith/setup-python@v6
-              with:
-                  python-version: ${{ matrix.python-version }}
-                  allow-prereleases: true
-                  cache: 'pip'
-                  cache-dependency-path: '**/setup.py'
-
-          -   name: Install tox
-              run: python -m pip install --upgrade pip 'tox' tox-gh-actions
-
-          -   name: >
-                  Run tox for
-                  "${{ matrix.python-version }}-integration-${{ matrix.toxenv }}"
-              uses: nick-fields/retry@v3
-              with:
-                timeout_minutes: 60
-                max_attempts: 2
-                retry_wait_seconds: 0
-                command: |
-                  tox -r --verbose --verbose -e "${{ matrix.python-version }}-integration-${{ matrix.toxenv }}" -vv
+        - name: Run tox for "${{ matrix.python-version }}-integration-${{ matrix.toxenv }}"
+          uses: nick-fields/retry@v3
+          with:
+            timeout_minutes: 60
+            max_attempts: 2
+            retry_wait_seconds: 0
+            command: |
+              tox -r --verbose --verbose -e "${{ matrix.python-version }}-integration-${{ matrix.toxenv }}" -vv
 
   Smoke:
     needs:
